"""rides table

Revision ID: 6853c5f39e7a
Revises: c4b7d9087210
Create Date: 2022-03-31 17:34:53.098992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6853c5f39e7a'
down_revision = 'c4b7d9087210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_plate', sa.String(), nullable=False),
    sa.Column('passenger_cpf', sa.String(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['passenger_cpf'], ['people.cpf'], ),
    sa.ForeignKeyConstraint(['vehicle_plate'], ['vehicles.plate'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rides')
    # ### end Alembic commands ###
